import { db } from "@workspace/db";
import {
  staffTable,
  clientsTable,
  engagementsTable,
  anomaliesTable,
  findingsTable,
  workingPapersTable,
  dataRoomTable,
} from "@workspace/db/schema";

async function seed() {
  console.log("Seeding AuditOS database...");

  // Staff
  const staff = await db.insert(staffTable).values([
    { fullName: "Dr. Amina Hassan", email: "amina.hassan@auditpro.co.tz", role: "partner", nbaaMemberNo: "NBAA-0042", isActive: true },
    { fullName: "James Mwangi", email: "james.mwangi@auditpro.co.tz", role: "manager", nbaaMemberNo: "NBAA-0189", isActive: true },
    { fullName: "Grace Kimaro", email: "grace.kimaro@auditpro.co.tz", role: "senior", nbaaMemberNo: "NBAA-0312", isActive: true },
    { fullName: "Patrick Osei", email: "patrick.osei@auditpro.co.tz", role: "senior", nbaaMemberNo: "NBAA-0445", isActive: true },
    { fullName: "Fatuma Ndege", email: "fatuma.ndege@auditpro.co.tz", role: "partner", nbaaMemberNo: "NBAA-0061", isActive: true },
  ]).returning();

  console.log(`Created ${staff.length} staff members`);

  // Clients
  const clients = await db.insert(clientsTable).values([
    {
      name: "Tanzania Breweries Ltd",
      tin: "100-123-456",
      industry: "Manufacturing",
      entityType: "Public Company",
      financialYearEnd: "December 31",
      contactName: "Robert Nkya",
      contactEmail: "r.nkya@tbl.co.tz",
      contactPhone: "+255 22 211 0000",
    },
    {
      name: "Azania Bank Ltd",
      tin: "100-234-567",
      industry: "Banking & Finance",
      entityType: "Public Company",
      financialYearEnd: "December 31",
      contactName: "Sophia Mmari",
      contactEmail: "s.mmari@azaniabank.co.tz",
      contactPhone: "+255 22 212 0000",
    },
    {
      name: "Kilimo Kwanza Cooperative",
      tin: "100-345-678",
      industry: "Agriculture",
      entityType: "Cooperative Society",
      financialYearEnd: "June 30",
      contactName: "Emmanuel Msigwa",
      contactEmail: "e.msigwa@kilimokwanza.co.tz",
      contactPhone: "+255 27 250 0000",
    },
    {
      name: "Dar es Salaam Rapid Transit Authority",
      tin: "100-456-789",
      industry: "Public Sector",
      entityType: "Government Agency",
      financialYearEnd: "June 30",
      contactName: "Brigadier (Rtd) Ahmed Khamis",
      contactEmail: "a.khamis@dart.go.tz",
      contactPhone: "+255 22 260 0000",
    },
    {
      name: "Serengeti Breweries Ltd",
      tin: "100-567-890",
      industry: "Manufacturing",
      entityType: "Private Company",
      financialYearEnd: "December 31",
      contactName: "Clara Wambura",
      contactEmail: "c.wambura@serengeti.co.tz",
      contactPhone: "+255 22 215 0000",
    },
  ]).returning();

  console.log(`Created ${clients.length} clients`);

  const partner1 = staff[0].id;
  const partner2 = staff[4].id;
  const manager = staff[1].id;
  const senior1 = staff[2].id;

  // Engagements
  const engagements = await db.insert(engagementsTable).values([
    {
      clientId: clients[0].id,
      engagementName: "Tanzania Breweries FY2024 Statutory Audit",
      periodStart: "2024-01-01",
      periodEnd: "2024-12-31",
      engagementType: "statutory_audit",
      status: "fieldwork",
      overallRisk: "high",
      materialityUsd: 850000,
      performanceMatUsd: 637500,
      partnerId: partner1,
      managerId: manager,
      reportDate: "2025-03-31",
      notes: "Listed entity — additional ISA 600 considerations for group audit components.",
    },
    {
      clientId: clients[1].id,
      engagementName: "Azania Bank FY2024 Statutory Audit",
      periodStart: "2024-01-01",
      periodEnd: "2024-12-31",
      engagementType: "statutory_audit",
      status: "review",
      overallRisk: "critical",
      materialityUsd: 2100000,
      performanceMatUsd: 1575000,
      partnerId: partner2,
      managerId: manager,
      reportDate: "2025-04-15",
      notes: "Bank of Tanzania regulated entity. IFRS 9 expected credit losses require specialist involvement.",
    },
    {
      clientId: clients[2].id,
      engagementName: "Kilimo Kwanza FY2024 Annual Audit",
      periodStart: "2024-07-01",
      periodEnd: "2025-06-30",
      engagementType: "statutory_audit",
      status: "planning",
      overallRisk: "medium",
      materialityUsd: 120000,
      performanceMatUsd: 90000,
      partnerId: partner1,
      managerId: manager,
      reportDate: "2025-09-30",
      notes: "First year audit engagement. Need to establish opening balances with predecessor auditors.",
    },
    {
      clientId: clients[3].id,
      engagementName: "DART FY2024 Performance Audit",
      periodStart: "2024-07-01",
      periodEnd: "2025-06-30",
      engagementType: "internal_audit",
      status: "fieldwork",
      overallRisk: "high",
      materialityUsd: 500000,
      performanceMatUsd: 375000,
      partnerId: partner2,
      managerId: senior1,
      reportDate: "2025-08-31",
      notes: "Public interest entity. Controller and Auditor General coordination required.",
    },
    {
      clientId: clients[4].id,
      engagementName: "Serengeti Breweries FY2023 Tax Review",
      periodStart: "2023-01-01",
      periodEnd: "2023-12-31",
      engagementType: "tax_review",
      status: "completed",
      overallRisk: "low",
      materialityUsd: 200000,
      performanceMatUsd: 150000,
      partnerId: partner1,
      managerId: manager,
      reportDate: "2024-06-30",
      notes: "Completed. Final report issued and accepted by client.",
    },
  ]).returning();

  console.log(`Created ${engagements.length} engagements`);

  // Anomalies for first two active engagements
  const anomalies = await db.insert(anomaliesTable).values([
    {
      engagementId: engagements[0].id,
      anomalyType: "round_number",
      riskLevel: "high",
      accountCode: "5100",
      accountName: "Raw Materials Expense",
      journalRef: "JV-2024-08-4412",
      transactionDate: "2024-08-15",
      amount: 1500000.00,
      description: "Round-number debit of USD 1,500,000 to Raw Materials with no supporting purchase order reference",
      aiExplanation: "This transaction exhibits a round-number anomaly (USD 1,500,000 exactly) to Raw Materials Expense with no PO reference. Round-number transactions significantly above materiality warrant investigation for fictitious purchases or pre-payment of goods not yet received. Risk of overstatement of expenses and understatement of inventory.",
      auditorStatus: "unreviewed",
    },
    {
      engagementId: engagements[0].id,
      anomalyType: "weekend_entry",
      riskLevel: "critical",
      accountCode: "2010",
      accountName: "Accounts Payable — Trade",
      journalRef: "JV-2024-09-5521",
      transactionDate: "2024-09-14",
      amount: 875400.00,
      description: "Journal entry posted Saturday 14 September at 23:47 crediting Accounts Payable with no approver ID",
      aiExplanation: "Weekend posting outside business hours by an unidentified user is a significant red flag for management override of controls (ISA 240.32). The absence of an approver ID suggests the entry bypassed the dual-authorisation workflow. This combination warrants immediate escalation and forensic tracing of the posting user account.",
      auditorStatus: "investigated",
      auditorNotes: "IT confirmed user 'sysadmin' account was used. CFO states it was an automated interface batch — awaiting system log confirmation.",
    },
    {
      engagementId: engagements[0].id,
      anomalyType: "duplicate",
      riskLevel: "medium",
      accountCode: "6200",
      accountName: "Marketing & Promotion",
      journalRef: "JV-2024-07-3301",
      transactionDate: "2024-07-03",
      amount: 245000.00,
      description: "Possible duplicate payment — same vendor (Bora Media Ltd), same amount, two days apart (Jul 1 and Jul 3)",
      aiExplanation: "Two identical payments of TZS 245,000 to Bora Media Ltd within 48 hours with sequential invoice numbers (BML-2024-441 and BML-2024-442) suggests either duplicate invoicing by vendor or duplicate processing by accounts payable. Obtain original invoices and confirm whether two separate deliverables were received.",
      auditorStatus: "cleared",
      auditorNotes: "Confirmed with vendor: two separate campaign invoices for July and August activation. Cleared.",
    },
    {
      engagementId: engagements[0].id,
      anomalyType: "large_reversal",
      riskLevel: "high",
      accountCode: "4000",
      accountName: "Revenue — Beer Sales",
      journalRef: "JV-2024-10-6644",
      transactionDate: "2024-10-31",
      amount: 3200000.00,
      description: "Year-end revenue reversal of USD 3.2M on 31 October — last day of Q3 reporting period",
      aiExplanation: "A large revenue reversal on the last day of a reporting period is a classic earnings management indicator under ISA 240 and SEC guidance. The USD 3.2M reversal (0.38% of annual revenue) is above performance materiality. Auditors should obtain the original recognition basis, the reversal rationale signed by CFO, and verify Q4 re-recognition if applicable.",
      auditorStatus: "finding",
    },
    {
      engagementId: engagements[1].id,
      anomalyType: "outlier",
      riskLevel: "critical",
      accountCode: "1520",
      accountName: "Loans & Advances — Corporate",
      journalRef: "JV-2024-06-9901",
      transactionDate: "2024-06-28",
      amount: 12500000.00,
      description: "Corporate loan disbursement 4.2 standard deviations above mean — no credit committee minutes on file",
      aiExplanation: "A corporate loan disbursement of USD 12.5M that is 4.2 standard deviations above the mean disbursement size is statistically extreme. Combined with missing credit committee minutes, this triggers ISA 315 fraud risk indicators relating to related-party transactions and management override. Requires immediate review of credit approval chain, borrower identification, and Bank of Tanzania large exposure reporting.",
      auditorStatus: "unreviewed",
    },
    {
      engagementId: engagements[1].id,
      anomalyType: "sequence_gap",
      riskLevel: "medium",
      accountCode: "7100",
      accountName: "Interest Income",
      journalRef: "JV-2024-05-7701",
      transactionDate: "2024-05-15",
      amount: 445000.00,
      description: "Gap in loan reference sequence — 47 loan IDs missing between LN-2024-1200 and LN-2024-1248",
      aiExplanation: "A sequence gap of 47 loan IDs may indicate: (1) voided or cancelled loans not properly written off, (2) loans disbursed off-system, or (3) interest income accruals without underlying loan documentation. Cross-reference the core banking system's void log and request reconciliation of all cancelled loan IDs.",
      auditorStatus: "investigated",
      auditorNotes: "IT audit trail obtained. 32 of 47 gaps are explained by test loans in staging environment that were migrated. Remaining 15 under investigation.",
    },
    {
      engagementId: engagements[3].id,
      anomalyType: "round_number",
      riskLevel: "medium",
      accountCode: "8200",
      accountName: "Infrastructure Maintenance",
      journalRef: "JV-2025-01-1101",
      transactionDate: "2025-01-10",
      amount: 750000.00,
      description: "Maintenance contract rounded to USD 750,000 — single source procurement with no tender documentation",
      aiExplanation: "Single-source procurement of USD 750,000 without competitive tender documentation violates the Public Procurement Act, 2011 (Tanzania) threshold. This is a significant compliance finding for a government agency and should be reported to the Procurement Regulatory Authority of Tanzania (PPRA).",
      auditorStatus: "finding",
    },
  ]).returning();

  console.log(`Created ${anomalies.length} anomalies`);

  // Findings
  const findings = await db.insert(findingsTable).values([
    {
      engagementId: engagements[0].id,
      anomalyId: anomalies[3].id,
      findingRef: "FIND-001",
      title: "Improper Year-End Revenue Reversal Without Adequate Documentation",
      description: "A revenue reversal of USD 3.2 million was posted on 31 October 2024 (last day of Q3) without adequate supporting documentation or CFO sign-off. This represents a potential earnings management risk and violates the entity's revenue recognition policy under IFRS 15.",
      riskLevel: "high",
      isaReference: "ISA 240.32, ISA 315.26",
      nbaaReference: "NBAA Audit Guideline 7",
      status: "open",
      dueDate: "2025-02-28",
      raisedBy: senior1,
    },
    {
      engagementId: engagements[1].id,
      anomalyId: anomalies[4].id,
      findingRef: "FIND-002",
      title: "Large Corporate Loan Disbursed Without Credit Committee Approval",
      description: "A corporate loan of USD 12.5 million was disbursed on 28 June 2024 without evidence of credit committee review or approval. Bank of Tanzania Prudential Guidelines require credit committee approval for all facilities exceeding USD 5 million.",
      riskLevel: "critical",
      isaReference: "ISA 315.15, ISA 500.A1",
      nbaaReference: "NBAA Professional Standard 12",
      status: "management_response",
      managementResponse: "Management has confirmed that the credit committee met on 27 June 2024 and the minutes were not uploaded to the system due to a technical issue. Minutes have now been retrieved from physical files and will be digitised.",
      dueDate: "2025-01-31",
      raisedBy: manager,
    },
    {
      engagementId: engagements[3].id,
      anomalyId: anomalies[6].id,
      findingRef: "FIND-003",
      title: "Non-Compliant Single-Source Procurement Exceeding Threshold",
      description: "DART awarded a maintenance contract for USD 750,000 through single-source procurement without obtaining required approvals from the Procurement Regulatory Authority of Tanzania (PPRA). This violates Section 65 of the Public Procurement Act, 2011.",
      riskLevel: "high",
      isaReference: "ISA 250.14",
      nbaaReference: "NBAA Government Audit Standard 3",
      status: "escalated",
      dueDate: "2025-03-31",
      raisedBy: partner2,
    },
  ]).returning();

  console.log(`Created ${findings.length} findings`);

  // Working Papers
  const workingPapers = await db.insert(workingPapersTable).values([
    {
      engagementId: engagements[0].id,
      wpRef: "WP-A100",
      section: "planning",
      title: "Engagement Acceptance and Continuance",
      status: "signed_off",
      contentText: "Engagement acceptance procedures completed in accordance with ISQC 1. Client background, independence checks, and risk assessment completed. No independence threats identified.",
      preparedBy: senior1,
      preparedAt: "2024-10-15",
      reviewedBy: manager,
      reviewedAt: "2024-10-18",
      signedOffBy: partner1,
      signedOffAt: "2024-10-20",
    },
    {
      engagementId: engagements[0].id,
      wpRef: "WP-A200",
      section: "planning",
      title: "Overall Audit Strategy and Plan",
      status: "reviewed",
      contentText: "Overall audit strategy developed based on preliminary risk assessment. Materiality set at USD 850,000 (1% of gross revenue). Performance materiality set at USD 637,500. Key audit matters identified: (1) Revenue recognition timing, (2) Raw materials valuation, (3) Related party transactions.",
      preparedBy: manager,
      preparedAt: "2024-10-22",
      reviewedBy: partner1,
      reviewedAt: "2024-10-25",
    },
    {
      engagementId: engagements[0].id,
      wpRef: "WP-B100",
      section: "controls",
      title: "Understanding and Evaluation of Internal Controls — Revenue Cycle",
      status: "prepared",
      preparedBy: senior1,
      preparedAt: "2024-11-05",
    },
    {
      engagementId: engagements[0].id,
      wpRef: "WP-C100",
      section: "substantive",
      title: "Revenue Substantive Testing — Beer Sales",
      status: "draft",
    },
    {
      engagementId: engagements[1].id,
      wpRef: "WP-A100",
      section: "planning",
      title: "Engagement Acceptance and Continuance — Azania Bank",
      status: "signed_off",
      preparedBy: manager,
      preparedAt: "2024-09-10",
      reviewedBy: partner2,
      reviewedAt: "2024-09-12",
      signedOffBy: partner2,
      signedOffAt: "2024-09-14",
    },
    {
      engagementId: engagements[1].id,
      wpRef: "WP-C200",
      section: "substantive",
      title: "Expected Credit Loss (ECL) Model Review — IFRS 9",
      status: "prepared",
      preparedBy: senior1,
      preparedAt: "2025-01-15",
    },
    {
      engagementId: engagements[2].id,
      wpRef: "WP-A100",
      section: "planning",
      title: "Predecessor Auditor Communication",
      status: "draft",
    },
  ]).returning();

  console.log(`Created ${workingPapers.length} working papers`);

  // Data Room Items
  await db.insert(dataRoomTable).values([
    {
      engagementId: engagements[0].id,
      category: "Financial Statements",
      itemName: "Draft Financial Statements FY2024",
      description: "Full set of draft financial statements including P&L, Balance Sheet, Cash Flow, and Notes",
      status: "received",
      receivedAt: "2025-01-10",
      fileName: "TBL_FS_FY2024_Draft.xlsx",
      dueDate: "2025-01-05",
      requestedBy: manager,
    },
    {
      engagementId: engagements[0].id,
      category: "General Ledger",
      itemName: "Trial Balance — December 2024",
      description: "Full trial balance as at 31 December 2024",
      status: "reviewed",
      receivedAt: "2025-01-08",
      fileName: "TBL_TB_Dec2024.csv",
      dueDate: "2025-01-07",
      requestedBy: senior1,
    },
    {
      engagementId: engagements[0].id,
      category: "Contracts & Agreements",
      itemName: "Raw Materials Supply Contracts",
      description: "All material supply contracts with values > USD 500,000",
      status: "requested",
      dueDate: "2025-02-01",
      requestedBy: senior1,
    },
    {
      engagementId: engagements[0].id,
      category: "Board Minutes",
      itemName: "Board of Directors Minutes — FY2024",
      description: "All board minutes for the financial year",
      status: "received",
      receivedAt: "2025-01-20",
      fileName: "TBL_BoardMinutes_2024.pdf",
      dueDate: "2025-01-15",
      requestedBy: manager,
    },
    {
      engagementId: engagements[1].id,
      category: "Regulatory",
      itemName: "Bank of Tanzania Inspection Report 2024",
      description: "Most recent BoT on-site inspection report",
      status: "queried",
      dueDate: "2025-01-20",
      requestedBy: partner2,
    },
    {
      engagementId: engagements[1].id,
      category: "Loan Portfolio",
      itemName: "Loan Portfolio Schedule — December 2024",
      description: "Complete loan book with aging, classification, and ECL provision",
      status: "received",
      receivedAt: "2025-01-12",
      fileName: "AzanaBank_LoanPortfolio_Dec2024.xlsx",
      dueDate: "2025-01-10",
      requestedBy: senior1,
    },
    {
      engagementId: engagements[3].id,
      category: "Procurement",
      itemName: "Procurement Register FY2025 H1",
      description: "All procurement transactions above TZS 10 million",
      status: "received",
      receivedAt: "2025-02-01",
      fileName: "DART_Procurement_FY2025H1.xlsx",
      dueDate: "2025-01-25",
      requestedBy: senior1,
    },
  ]);

  console.log("Data room items created");
  console.log("\nSeeding complete!");
}

seed().catch(console.error).finally(() => process.exit(0));
